// Generated fixture copy — do not edit by hand. Everything below the import
// must stay byte-identical to the output of
// `generateSchemaSource(named: "GeneratedFixtureSchema")` for
// Fixtures/data_binding_test.riv; `SchemaGenerationTests` guards the match and
// prints the fresh source to copy over on drift.
import SwiftyRive

// Generated by SwiftyRive from the default artboard. Verify with document.validate(_:artboard:).

nonisolated enum Test: String, RiveEnum {
    case baz = "Baz"
    case bar = "Bar"
    case foo = "Foo"
}

nonisolated struct GeneratedFixtureSchema: RiveSchema {
    let string = RiveKey<String>("SecondNested/DeeperNested/String")
    let secondNestedString = RiveKey<String>("SecondNested/String")
    let triggerBlue = RiveTriggerKey("Trigger Blue")
    let triggerGreen = RiveTriggerKey("Trigger Green")
    let triggerRed = RiveTriggerKey("Trigger Red")
    let deeperNestedString = RiveKey<String>("Nested/DeeperNested/String")
    let nestedString = RiveKey<String>("Nested/String")
    let `enum` = RiveKey<Test>("Enum")
    let color = RiveKey<RiveColor>("Color")
    let boolean = RiveKey<Bool>("Boolean")
    let number = RiveKey<Double>("Number")
    let string2 = RiveKey<String>("String")

    // unsupported (list): List
    // unsupported (image): Image
}
