import Foundation
import Testing
@testable import SwiftyRive

/// Tests for ``RiveDocument/generateSchemaSource(named:artboard:viewModel:)``.
///
/// The round-trip quality gate works through ``GeneratedFixtureSchema``: a
/// committed copy of the generator's output that the test target *compiles*,
/// an equality test that fails on any drift between generator and copy, and a
/// validation test proving the generated schema matches the fixture file.
struct SchemaGenerationTests {
    @Test func generatedSourceContainsExpectedKeys() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let source = try await document.generateSchemaSource()

        #expect(source.hasPrefix("// Generated by SwiftyRive from the default artboard. Verify with document.validate(_:artboard:)."))
        #expect(source.contains("nonisolated struct GeneratedSchema: RiveSchema {"))

        // Kind → key type mapping.
        #expect(source.contains(#"let number = RiveKey<Double>("Number")"#))
        #expect(source.contains(#"let boolean = RiveKey<Bool>("Boolean")"#))
        #expect(source.contains(#"let color = RiveKey<RiveColor>("Color")"#))
        #expect(source.contains(#"let triggerRed = RiveTriggerKey("Trigger Red")"#))

        // The fixture's enum is named "Test"; case names get lowerCamel names
        // with raw values preserving the file's strings.
        #expect(source.contains("nonisolated enum Test: String, RiveEnum {"))
        #expect(source.contains(#"case foo = "Foo""#))
        #expect(source.contains(#"let `enum` = RiveKey<Test>("Enum")"#))

        // Nested paths are preserved in the key path string.
        #expect(source.contains(#"let nestedString = RiveKey<String>("Nested/String")"#))

        // Name collisions resolve via parent segment, then numeric suffix.
        #expect(source.contains(#"let string = RiveKey<String>("SecondNested/DeeperNested/String")"#))
        #expect(source.contains(#"let deeperNestedString = RiveKey<String>("Nested/DeeperNested/String")"#))
        #expect(source.contains(#"let string2 = RiveKey<String>("String")"#))

        // Unsupported kinds become a trailing comment block, not keys.
        #expect(source.contains("// unsupported (list): List"))
        #expect(source.contains("// unsupported (image): Image"))
        #expect(source.contains("RiveKey") == true)
        #expect(source.contains(#""List""#) == false)
        #expect(source.contains(#""Image""#) == false)
    }

    @Test func explicitViewModelPinsViewModelName() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let source = try await document.generateSchemaSource(viewModel: "Test")
        #expect(source.contains(#"static var viewModelName: String? { "Test" }"#))
    }

    @Test func artboardIsNamedInTheHeader() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let source = try await document.generateSchemaSource(artboard: "Artboard")
        #expect(source.hasPrefix(#"// Generated by SwiftyRive from artboard "Artboard"."#))
    }

    @Test func typeNameIsSanitized() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let source = try await document.generateSchemaSource(named: "my robot schema")
        #expect(source.contains("nonisolated struct MyRobotSchema: RiveSchema {"))
    }

    @Test func outputIsDeterministic() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let first = try await document.generateSchemaSource()
        let second = try await document.generateSchemaSource()
        #expect(first == second)
    }

    @Test func unknownArtboardAndViewModelFailLikeDiscovery() async throws {
        let document = try await Fixtures.dataBindingDocument()
        await expectArtboardNotFound(name: "Missing", available: ["Artboard"]) {
            _ = try await document.generateSchemaSource(artboard: "Missing")
        }
        await #expect(throws: RiveSchemaError.self) {
            _ = try await document.generateSchemaSource(viewModel: "Missing")
        }
    }

    // MARK: - Round trip

    /// The committed ``GeneratedFixtureSchema`` copy must stay byte-identical
    /// to the generator's current output — on drift, recopy the source this
    /// test prints into GeneratedFixtureSchema.swift (below the import).
    @Test func committedFixtureCopyMatchesGeneratedSource() async throws {
        let document = try await Fixtures.dataBindingDocument()
        let source = try await document.generateSchemaSource(named: "GeneratedFixtureSchema")

        let fixtureURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("GeneratedFixtureSchema.swift")
        let committed = try String(contentsOf: fixtureURL, encoding: .utf8)
        #expect(
            committed.hasSuffix("\n\(source)"),
            "GeneratedFixtureSchema.swift drifted — replace everything below its import with:\n\(source)"
        )
    }

    /// The committed copy compiles (this target builds it) *and* validates
    /// against the fixture file — proving generated schemas round-trip.
    @Test func committedFixtureCopyValidatesAgainstTheFixture() async throws {
        let document = try await Fixtures.dataBindingDocument()
        try await document.validate(GeneratedFixtureSchema.self)

        let instance = try await document.makeInstance(of: GeneratedFixtureSchema.self)
        instance[\.string2] = "round trip"
        #expect(instance[\.string2] == "round trip")
    }

    // MARK: - Identifier sanitization

    @Test func lowerCamelIdentifierSanitizes() {
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "Item_Value_Icon") == "itemValueIcon")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "Trigger Red") == "triggerRed")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "DeeperNested") == "deeperNested")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "hello-world!") == "helloWorld")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "2nd Item") == "_2ndItem")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "***") == "property")
        #expect(SchemaSourceNaming.lowerCamelIdentifier(from: "") == "property")
    }

    @Test func upperCamelIdentifierSanitizes() {
        #expect(SchemaSourceNaming.upperCamelIdentifier(from: "item selection") == "ItemSelection")
        #expect(SchemaSourceNaming.upperCamelIdentifier(from: "colors") == "Colors")
        #expect(SchemaSourceNaming.upperCamelIdentifier(from: "1: Ordinal") == "_1Ordinal")
        #expect(SchemaSourceNaming.upperCamelIdentifier(from: " ") == "Value")
    }

    @Test func reservedWordsAreBacktickEscaped() {
        #expect(SchemaSourceNaming.escaped("enum") == "`enum`")
        #expect(SchemaSourceNaming.escaped("default") == "`default`")
        #expect(SchemaSourceNaming.escaped("mood") == "mood")
    }

    @Test func stringLiteralsEscapeSpecialCharacters() {
        #expect(SchemaSourceNaming.stringLiteral("plain") == #""plain""#)
        #expect(SchemaSourceNaming.stringLiteral(#"a "b" \c"#) == #""a \"b\" \\c""#)
        #expect(SchemaSourceNaming.stringLiteral("line\nbreak") == #""line\nbreak""#)
    }

    @Test func namePoolDeduplicatesDeterministically() {
        var pool = SchemaSourceNaming.NamePool()
        #expect(pool.claim(["string"]) == "string")
        #expect(pool.claim(["string", "nestedString"]) == "nestedString")
        #expect(pool.claim(["string", "nestedString"]) == "nestedString2")
        #expect(pool.claim(["string"]) == "string2")
        #expect(pool.claim(["string"]) == "string3")
    }
}
